### PR TITLE
Supported GHC 8.10.7.

### PR DESCRIPTION
**Pull request by asr**

### CODE REVIEW

**Comment by andreasabel** [comment]
Looks like it is still a bit too early for CI with GHC 8.10.7.

**Comment by asr** [comment]
> Looks like it is still a bit too early for CI with GHC 8.10.7.

It depends of CI's configuration. I hadn't problems with `fix-whitespace`.

**Comment by andreasabel** [comment]
Ok, I switched from `hvr-ppa` to `ghcup` for 8.10.7.  See `cabal.haskell-ci` for the configuration.

**Comment by andreasabel** [comment]
@asr:  Thanks for merging!
Questions:
- Does mere _testing_ on a new GHC version warrant a release?  After all, we only updated the CI (and some `stack-*.yaml` files).
- Why should we delete `stack-*.yaml` files for old minor versions?  (They still work and could be used with `stack --system-ghc` and old installed compilers.)
- Stepping back, why do we maintain `stack-*.yaml` files here at all?  `hs-tags` can be installed from stackage directly.  On `agda/agda`, we have these files for running the `stack`-CI, but here we do not have one.

**Pull request merged**
